// Auto-generated by extract-feats.js
// Do not edit manually

export const BOOKS = {
  "phb": "Player's Handbook",
  "hof": "Heroes of Faerûn",
  "fef": "Fifth Edition Feats",
  "echh": "Epic Characters & Heroes Handbook"
};

export const ABILITIES = [
  "Strength",
  "Dexterity",
  "Constitution",
  "Intelligence",
  "Wisdom",
  "Charisma"
];

export const FEATS = [
  {
    "name": "Alert",
    "book": "phb",
    "category": "General"
  },
  {
    "name": "Crafter",
    "book": "phb",
    "category": "General"
  },
  {
    "name": "Cult of the Dragon Initiate",
    "book": "hof",
    "category": "General"
  },
  {
    "name": "Emerald Enclave Fledgling",
    "book": "hof",
    "category": "General"
  },
  {
    "name": "Harper Agent",
    "book": "hof",
    "category": "General"
  },
  {
    "name": "Healer",
    "book": "phb",
    "category": "General"
  },
  {
    "name": "Lords' Alliance Agent",
    "book": "hof",
    "category": "General"
  },
  {
    "name": "Lucky",
    "book": "phb",
    "category": "General"
  },
  {
    "name": "Magic Initiate",
    "book": "phb",
    "category": "General"
  },
  {
    "name": "Musician",
    "book": "phb",
    "category": "General"
  },
  {
    "name": "Purple Dragon Rook",
    "book": "hof",
    "category": "General"
  },
  {
    "name": "Savage Attacker",
    "book": "phb",
    "youGain": "{false}",
    "category": "General"
  },
  {
    "name": "Skilled",
    "book": "phb",
    "youGain": "{false}",
    "category": "General"
  },
  {
    "name": "Spellfire Spark",
    "book": "hof",
    "category": "General"
  },
  {
    "name": "Tavern Brawler",
    "book": "phb",
    "category": "General"
  },
  {
    "name": "Tough",
    "book": "phb",
    "youGain": "{false}",
    "category": "General"
  },
  {
    "name": "Tyro of the Gauntlet",
    "book": "hof",
    "category": "General"
  },
  {
    "name": "Zhentarim Ruffian",
    "book": "hof",
    "category": "General"
  },
  {
    "name": "Active Alchemy",
    "book": "echh",
    "abilityIncrease": [
      "Wisdom",
      "Intelligence"
    ],
    "youGain": "You",
    "category": "General"
  },
  {
    "name": "Actor",
    "book": "phb",
    "abilityIncrease": [
      "Charisma"
    ],
    "prerequisite": "Charisma 13+",
    "category": "General"
  },
  {
    "name": "Adrenaline Surge",
    "book": "phb",
    "abilityIncrease": [
      "Strength",
      "Constitution"
    ],
    "youGain": "{false}",
    "category": "General"
  },
  {
    "name": "Arcane Shield",
    "book": "fef",
    "prerequisite": "Ability to cast arcane spells",
    "youGain": "{false}",
    "category": "General"
  },
  {
    "name": "Arcane Strike",
    "book": "fef",
    "prerequisite": "Ability to cast arcane spells.",
    "youGain": "{false}",
    "category": "General"
  },
  {
    "name": "Athlete",
    "book": "phb",
    "abilityIncrease": [
      "Strength",
      "Dexterity"
    ],
    "prerequisite": "Strength or Dexterity 13+",
    "category": "General"
  },
  {
    "name": "Augmented Conjuring",
    "book": "fef",
    "prerequisite": "Spell Focus (Conjuration)",
    "youGain": "{false}",
    "category": "General"
  },
  {
    "name": "Battlecaster",
    "book": "fef",
    "prerequisite": "The ability to cast at least one spell.",
    "youGain": "{false}",
    "category": "General"
  },
  {
    "name": "Battlefield Trickster",
    "book": "fef",
    "abilityIncrease": [
      "Strength",
      "Dexterity"
    ],
    "youGain": "{false}",
    "category": "General"
  },
  {
    "name": "Blaster Buffet",
    "book": "fef",
    "youGain": "{false}",
    "category": "General"
  },
  {
    "name": "Blowgun Injector",
    "book": "fef",
    "abilityIncrease": [
      "Dexterity"
    ],
    "youGain": "{false}",
    "category": "General"
  },
  {
    "name": "Charger",
    "book": "phb",
    "abilityIncrease": [
      "Strength",
      "Dexterity"
    ],
    "prerequisite": "Strength or Dexterity 13+",
    "category": "General"
  },
  {
    "name": "Chef",
    "book": "phb",
    "abilityIncrease": [
      "Constitution",
      "Wisdom"
    ],
    "category": "General"
  },
  {
    "name": "Cold Caster",
    "book": "hof",
    "abilityIncrease": [
      "Charisma",
      "Wisdom",
      "Intelligence"
    ],
    "category": "General"
  },
  {
    "name": "Combat Caster",
    "book": "fef",
    "youGain": "{false}",
    "category": "General"
  },
  {
    "name": "Combat Expertise",
    "book": "fef",
    "abilityIncrease": [
      "Dexterity"
    ],
    "prerequisite": "Dex 13+",
    "youGain": "{false}",
    "category": "General"
  },
  {
    "name": "Comeback Kid",
    "book": "fef",
    "abilityIncrease": [
      "Constitution"
    ],
    "youGain": "{false}",
    "category": "General"
  },
  {
    "name": "Conditioned Body",
    "book": "echh",
    "abilityIncrease": [
      "Constitution"
    ],
    "youGain": "{false}",
    "category": "General"
  },
  {
    "name": "Conditioning",
    "book": "echh",
    "abilityIncrease": [
      "Strength",
      "Constitution",
      "Dexterity"
    ],
    "youGain": "{false}",
    "category": "General"
  },
  {
    "name": "Counter-Riposte",
    "book": "fef",
    "abilityIncrease": [
      "Strength",
      "Dexterity"
    ],
    "youGain": "{false}",
    "category": "General"
  },
  {
    "name": "Crossbow Expert",
    "book": "phb",
    "abilityIncrease": [
      "Dexterity"
    ],
    "prerequisite": "Dexterity 13+",
    "category": "General"
  },
  {
    "name": "Crusher",
    "book": "phb",
    "abilityIncrease": [
      "Strength",
      "Constitution"
    ],
    "category": "General"
  },
  {
    "name": "Cunning Plan",
    "book": "echh",
    "youGain": "{false}",
    "category": "General"
  },
  {
    "name": "Defensive Duelist",
    "book": "phb",
    "abilityIncrease": [
      "Dexterity"
    ],
    "prerequisite": "Dexterity 13+",
    "category": "General"
  },
  {
    "name": "Desperate Reserve",
    "book": "echh",
    "abilityIncrease": [
      "Constitution"
    ],
    "category": "General"
  },
  {
    "name": "Dodging Expertise",
    "book": "fef",
    "prerequisite": "Dex 13+",
    "youGain": "{false}",
    "category": "General"
  },
  {
    "name": "Double Cast",
    "book": "fef",
    "prerequisite": "The ability to cast at least one cantrip",
    "youGain": "{false}",
    "category": "General"
  },
  {
    "name": "Down but not Out",
    "book": "fef",
    "abilityIncrease": [
      "Constitution"
    ],
    "youGain": "{false}",
    "category": "General"
  },
  {
    "name": "Downcaster",
    "book": "fef",
    "prerequisite": "Spellcasting feature",
    "youGain": "{false}",
    "category": "General"
  },
  {
    "name": "Dragonscarred",
    "book": "hof",
    "abilityIncrease": [
      "Constitution",
      "Charisma"
    ],
    "category": "General"
  },
  {
    "name": "Dual Wielder",
    "book": "phb",
    "abilityIncrease": [
      "Strength",
      "Dexterity"
    ],
    "prerequisite": "Strength or Dexterity 13+",
    "category": "General"
  },
  {
    "name": "Durable",
    "book": "phb",
    "abilityIncrease": [
      "Constitution"
    ],
    "category": "General"
  },
  {
    "name": "Eldritch Adept",
    "book": "fef",
    "prerequisite": "Spellcasting or Pact Magic Feature",
    "youGain": "{false}",
    "category": "General"
  },
  {
    "name": "Eldritch Lifesaver",
    "book": "echh",
    "prerequisite": "The ability to cast at least one arcane spell.",
    "youGain": "{false}",
    "category": "General"
  },
  {
    "name": "Elemental Adept",
    "book": "phb",
    "abilityIncrease": [
      "Charisma",
      "Wisdom",
      "Intelligence"
    ],
    "prerequisite": "Spellcasting or Pact Magic Feature",
    "category": "General"
  },
  {
    "name": "Elementary Expertise",
    "book": "echh",
    "prerequisite": "The ability to cast at least one spell",
    "youGain": "{false}",
    "category": "General"
  },
  {
    "name": "Enclave Magic",
    "book": "hof",
    "abilityIncrease": [
      "Charisma",
      "Wisdom",
      "Intelligence"
    ],
    "category": "General"
  },
  {
    "name": "Energy Recovery",
    "book": "echh",
    "prerequisite": "Spellcasting",
    "youGain": "{false}",
    "category": "General"
  },
  {
    "name": "Expert Tactician",
    "book": "echh",
    "abilityIncrease": [
      "Charisma"
    ],
    "youGain": "{false}",
    "category": "General"
  },
  {
    "name": "Expert Trapper",
    "book": "echh",
    "abilityIncrease": [
      "Wisdom"
    ],
    "youGain": "{false}",
    "category": "General"
  },
  {
    "name": "Fairy Trickster",
    "book": "hof",
    "abilityIncrease": [
      "Dexterity",
      "Charisma"
    ],
    "category": "General"
  },
  {
    "name": "Fast as Lightning",
    "book": "echh",
    "abilityIncrease": [
      "Dexterity"
    ],
    "youGain": "{false}",
    "category": "General"
  },
  {
    "name": "Fey-Touched",
    "book": "phb",
    "abilityIncrease": [
      "Charisma",
      "Wisdom",
      "Intelligence"
    ],
    "youGain": "Your",
    "category": "General"
  },
  {
    "name": "Fleet",
    "book": "fef",
    "abilityIncrease": [
      "Dexterity"
    ],
    "prerequisite": "Dex 15+",
    "youGain": "{false}",
    "category": "General"
  },
  {
    "name": "Genie Magic",
    "book": "hof",
    "abilityIncrease": [
      "Charisma",
      "Wisdom",
      "Intelligence"
    ],
    "category": "General"
  },
  {
    "name": "Grappler",
    "book": "phb",
    "abilityIncrease": [
      "Strength",
      "Dexterity"
    ],
    "prerequisite": "Strength or Dexterity 13+",
    "youGain": "{false}",
    "category": "General"
  },
  {
    "name": "Great Weapon Master",
    "book": "phb",
    "abilityIncrease": [
      "Strength"
    ],
    "prerequisite": "Strength 13+",
    "youGain": "{false}",
    "category": "General"
  },
  {
    "name": "Harper Teamwork",
    "book": "hof",
    "abilityIncrease": [
      "Dexterity",
      "Charisma"
    ],
    "youGain": "{false}",
    "category": "General"
  },
  {
    "name": "Heavily Armored",
    "book": "phb",
    "abilityIncrease": [
      "Strength",
      "Constitution"
    ],
    "prerequisite": "Medium Armor Proficiency",
    "youGain": "{false}",
    "category": "General"
  },
  {
    "name": "Heavy Armor Master",
    "book": "phb",
    "abilityIncrease": [
      "Strength",
      "Constitution"
    ],
    "prerequisite": "Heavy Armor Proficiency",
    "youGain": "{false}",
    "category": "General"
  },
  {
    "name": "Hulking Brute",
    "book": "echh",
    "prerequisite": "Strength 18+",
    "category": "General"
  },
  {
    "name": "Inspiring Leader",
    "book": "phb",
    "abilityIncrease": [
      "Charisma",
      "Wisdom"
    ],
    "prerequisite": "Wisdom or Charisma 13+",
    "category": "General"
  },
  {
    "name": "Invigorating Abjuration",
    "book": "echh",
    "prerequisite": "The ability to cast at least one spell",
    "youGain": "{false}",
    "category": "General"
  },
  {
    "name": "Keen Mind",
    "book": "phb",
    "abilityIncrease": [
      "Charisma",
      "Wisdom"
    ],
    "youGain": "{false}",
    "category": "General"
  },
  {
    "name": "Keep it Simple",
    "book": "echh",
    "abilityIncrease": [
      "Strength",
      "Dexterity"
    ],
    "youGain": "{false}",
    "category": "General"
  },
  {
    "name": "Larger than Life",
    "book": "echh",
    "abilityIncrease": [
      "Strength",
      "Constitution"
    ],
    "category": "General"
  },
  {
    "name": "Lightly Armored",
    "book": "phb",
    "abilityIncrease": [
      "Strength",
      "Dexterity"
    ],
    "category": "General"
  },
  {
    "name": "Lightning Stance",
    "book": "echh",
    "abilityIncrease": [
      "Dexterity"
    ],
    "youGain": "{false}",
    "category": "General"
  },
  {
    "name": "Lordly Resolve",
    "book": "echh",
    "abilityIncrease": [
      "Strength",
      "Charisma"
    ],
    "category": "General"
  },
  {
    "name": "Mage Killer",
    "book": "echh",
    "prerequisite": "Arcana proficiency",
    "youGain": "{false}",
    "category": "General"
  },
  {
    "name": "Mage Slayer",
    "book": "phb",
    "abilityIncrease": [
      "Strength",
      "Dexterity"
    ],
    "category": "General"
  },
  {
    "name": "Magical Prodigy",
    "book": "echh",
    "prerequisite": "Spellcasting or Pact Magic feature. Spellcasting ability score 16+",
    "youGain": "{false}",
    "category": "General"
  },
  {
    "name": "Magical Reminiscence",
    "book": "echh",
    "prerequisite": "The ability to cast at least one spell",
    "category": "General"
  },
  {
    "name": "Marksman",
    "book": "echh",
    "abilityIncrease": [
      "Dexterity"
    ],
    "youGain": "{false}",
    "category": "General"
  },
  {
    "name": "Martial Weapon Training",
    "book": "phb",
    "abilityIncrease": [
      "Strength",
      "Dexterity"
    ],
    "category": "General"
  },
  {
    "name": "Master of Magic",
    "book": "echh",
    "prerequisite": "Magical Prodigy feat. Spellcasting ability score 18+. Arcane spellcasting or Divine spellcasting.",
    "youGain": "{false}",
    "category": "General"
  },
  {
    "name": "Master of High Magic",
    "book": "echh",
    "prerequisite": "Master of Magic feat. Spellcasting ability score 18+. Arcane spellcasting or Divine spellcasting.",
    "youGain": "{false}",
    "category": "General"
  },
  {
    "name": "Meditation",
    "book": "echh",
    "abilityIncrease": [
      "Charisma",
      "Wisdom",
      "Intelligence"
    ],
    "youGain": "{false}",
    "category": "General"
  },
  {
    "name": "Medium Armor Master",
    "book": "phb",
    "abilityIncrease": [
      "Strength",
      "Dexterity"
    ],
    "prerequisite": "Medium Armor Proficiency",
    "category": "General"
  },
  {
    "name": "Metamagic Adept",
    "book": "echh",
    "prerequisite": "Spellcasting or Pact Magic feature",
    "youGain": "{false}",
    "category": "General"
  },
  {
    "name": "Metamagic: Preserved Spell",
    "book": "echh",
    "prerequisite": "Spellcasting ability score 16+",
    "youGain": "{false}",
    "category": "General"
  },
  {
    "name": "Moderately Armored",
    "book": "phb",
    "abilityIncrease": [
      "Strength",
      "Dexterity"
    ],
    "prerequisite": "Light Armor Proficiency",
    "category": "General"
  },
  {
    "name": "Mounted Combatant",
    "book": "phb",
    "abilityIncrease": [
      "Strength",
      "Wisdom",
      "Dexterity"
    ],
    "category": "General"
  },
  {
    "name": "Mythal Touched",
    "book": "hof",
    "abilityIncrease": [
      "Charisma",
      "Wisdom",
      "Intelligence"
    ],
    "category": "General"
  },
  {
    "name": "Nimble Physique",
    "abilityIncrease": [
      "Dexterity"
    ],
    "prerequisite": "Dexterity 14 or higher",
    "youGain": "{false}",
    "category": "General"
  },
  {
    "name": "Observant",
    "book": "phb",
    "abilityIncrease": [
      "Wisdom",
      "Intelligence"
    ],
    "prerequisite": "Intelligence or Wisdom 13+",
    "category": "General"
  },
  {
    "name": "Order's Resilience",
    "book": "hof",
    "abilityIncrease": [
      "Strength",
      "Charisma",
      "Wisdom"
    ],
    "prerequisite": "Prerequisite: Level 4+, Tyro of the Gauntlet Feat",
    "category": "General"
  },
  {
    "name": "Overly Prepared",
    "youGain": "{false}",
    "category": "General"
  },
  {
    "name": "Overwhelming Elemental Power",
    "abilityIncrease": [
      "Charisma",
      "Wisdom",
      "Intelligence"
    ],
    "prerequisite": "Elemental Adept Feat",
    "category": "General"
  },
  {
    "name": "Parry Spell",
    "prerequisite": "Dex 13+, Arcana proficiency",
    "youGain": "{false}",
    "category": "General"
  },
  {
    "name": "Parting Shot",
    "prerequisite": "Dex 15+",
    "youGain": "{false}",
    "category": "General"
  },
  {
    "name": "Piercer",
    "book": "phb",
    "abilityIncrease": [
      "Strength",
      "Dexterity"
    ],
    "category": "General"
  },
  {
    "name": "Poisoner",
    "book": "phb",
    "abilityIncrease": [
      "Dexterity",
      "Intelligence"
    ],
    "category": "General"
  },
  {
    "name": "Polearm Master",
    "book": "phb",
    "abilityIncrease": [
      "Dexterity",
      "Strength"
    ],
    "prerequisite": "Strength or Dexterity 13+",
    "category": "General"
  },
  {
    "name": "Precognitive",
    "book": "echh",
    "abilityIncrease": [
      "Wisdom"
    ],
    "prerequisite": "Wisdom 14+",
    "youGain": "{false}",
    "category": "General"
  },
  {
    "name": "Privilege of the Wise",
    "book": "echh",
    "abilityIncrease": [
      "Wisdom"
    ],
    "youGain": "{false}",
    "category": "General"
  },
  {
    "name": "Protective Transmutation",
    "book": "echh",
    "abilityIncrease": [
      "Intelligence",
      "Wisdom",
      "Charisma"
    ],
    "prerequisite": "The ability to cast at least one spell",
    "youGain": "{false}",
    "category": "General"
  },
  {
    "name": "Punisher",
    "book": "echh",
    "abilityIncrease": [
      "Strength",
      "Dexterity"
    ],
    "youGain": "{false}",
    "category": "General"
  },
  {
    "name": "Purple Dragon Commandant",
    "book": "hof",
    "abilityIncrease": [
      "Strength",
      "Dexterity"
    ],
    "prerequisite": "Prerequisite: Level 4+, Purple Dragon Rook Feat or Martial Weapon Proficiency",
    "category": "General"
  },
  {
    "name": "Quick Adaptation",
    "book": "echh",
    "abilityIncrease": [
      "Constitution"
    ],
    "youGain": "{false}",
    "category": "General"
  },
  {
    "name": "Reactive",
    "book": "echh",
    "abilityIncrease": [
      "Dexterity"
    ],
    "prerequisite": "Dexterity 18+, Fast as Lightning Feat",
    "youGain": "{false}",
    "category": "General"
  },
  {
    "name": "Resilient",
    "book": "phb",
    "abilityIncrease": [
      "Constitution"
    ],
    "category": "General"
  },
  {
    "name": "Ritual Caster",
    "book": "phb",
    "abilityIncrease": [
      "Charisma",
      "Wisdom",
      "Intelligence"
    ],
    "prerequisite": "Intelligence, Wisdom or Charisma 13+",
    "category": "General"
  },
  {
    "name": "Seeker of Seven Songs",
    "book": "echh",
    "abilityIncrease": [
      "Charisma"
    ],
    "youGain": "You",
    "category": "General"
  },
  {
    "name": "Sentinel",
    "book": "phb",
    "abilityIncrease": [
      "Strength",
      "Dexterity"
    ],
    "prerequisite": "Stength or Dexterity 13+",
    "category": "General"
  },
  {
    "name": "Shadow-Touched",
    "book": "phb",
    "abilityIncrease": [
      "Charisma",
      "Wisdom",
      "Intelligence"
    ],
    "youGain": "Your",
    "category": "General"
  },
  {
    "name": "Sharpshooter",
    "book": "phb",
    "abilityIncrease": [
      "Dexterity"
    ],
    "prerequisite": "Dexterity 13+",
    "category": "General"
  },
  {
    "name": "Shield Bearer",
    "book": "fef",
    "abilityIncrease": [
      "Strength",
      "Dexterity"
    ],
    "youGain": "{false}",
    "category": "General"
  },
  {
    "name": "Shield Master",
    "book": "phb",
    "abilityIncrease": [
      "Strength"
    ],
    "prerequisite": "Shield Proficiency",
    "category": "General"
  },
  {
    "name": "Sidestep",
    "book": "fef",
    "abilityIncrease": [
      "Dexterity"
    ],
    "youGain": "{false}",
    "category": "General"
  },
  {
    "name": "Skill Expert",
    "book": "phb",
    "abilityIncrease": [
      "Choice"
    ],
    "category": "General"
  },
  {
    "name": "Skulker",
    "book": "phb",
    "abilityIncrease": [
      "Dexterity"
    ],
    "prerequisite": "Dexterity 13+",
    "category": "General"
  },
  {
    "name": "Slasher",
    "book": "phb",
    "abilityIncrease": [
      "Strength",
      "Dexterity"
    ],
    "category": "General"
  },
  {
    "name": "Sleuthing",
    "book": "echh",
    "abilityIncrease": [
      "Intelligence"
    ],
    "youGain": "{false}",
    "category": "General"
  },
  {
    "name": "Speedy",
    "book": "phb",
    "abilityIncrease": [
      "Dexterity",
      "Constitution"
    ],
    "prerequisite": "Dexterity or Constitution 13+",
    "category": "General"
  },
  {
    "name": "Spellblade",
    "book": "echh",
    "abilityIncrease": [
      "Intelligence",
      "Wisdom",
      "Charisma"
    ],
    "prerequisite": "Spellcasting ability 15+",
    "youGain": "You’ve",
    "category": "General"
  },
  {
    "name": "Spellfire Adept",
    "book": "hof",
    "abilityIncrease": [
      "Charisma",
      "Wisdom",
      "Intelligence"
    ],
    "prerequisite": "Spellfire Spark Feat or the Spellcasting or Pact Magic Feature",
    "category": "General"
  },
  {
    "name": "Spell Focus",
    "book": "echh",
    "prerequisite": "Ability to cast spells.",
    "youGain": "{false}",
    "category": "General"
  },
  {
    "name": "Spellmarked",
    "book": "echh",
    "prerequisite": "Sorcerer",
    "youGain": "{false}",
    "category": "General"
  },
  {
    "name": "Spell Penetration",
    "book": "echh",
    "prerequisite": "Spell Focus Feat",
    "youGain": "{false}",
    "category": "General"
  },
  {
    "name": "Spell Sniper",
    "book": "phb",
    "abilityIncrease": [
      "Charisma",
      "Wisdom",
      "Intelligence"
    ],
    "prerequisite": "Spellcasting or Pact Magic Feature",
    "category": "General"
  },
  {
    "name": "Street Justice",
    "book": "hof",
    "abilityIncrease": [
      "Strength",
      "Dexterity"
    ],
    "category": "General"
  },
  {
    "name": "Strong Grip",
    "book": "echh",
    "abilityIncrease": [
      "Strength"
    ],
    "youGain": "{false}",
    "category": "General"
  },
  {
    "name": "Telekinetic",
    "book": "phb",
    "abilityIncrease": [
      "Charisma",
      "Wisdom",
      "Intelligence"
    ],
    "category": "General"
  },
  {
    "name": "Telepathic",
    "book": "phb",
    "abilityIncrease": [
      "Charisma",
      "Wisdom",
      "Intelligence"
    ],
    "category": "General"
  },
  {
    "name": "Tireless",
    "book": "echh",
    "abilityIncrease": [
      "Constitution"
    ],
    "category": "General"
  },
  {
    "name": "Torch Master",
    "book": "echh",
    "abilityIncrease": [
      "Strength",
      "Constitution",
      "Dexterity"
    ],
    "youGain": "{false}",
    "category": "General"
  },
  {
    "name": "Unrelenting Caster",
    "book": "echh",
    "abilityIncrease": [
      "Charisma",
      "Wisdom",
      "Intelligence"
    ],
    "prerequisite": "The ability to cast at least one spell",
    "youGain": "Whoever",
    "category": "General"
  },
  {
    "name": "Upcaster",
    "book": "echh",
    "abilityIncrease": [
      "Charisma",
      "Wisdom",
      "Intelligence"
    ],
    "prerequisite": "Spellcasting feature",
    "youGain": "{false}",
    "category": "General"
  },
  {
    "name": "War Caster",
    "book": "phb",
    "abilityIncrease": [
      "Charisma",
      "Wisdom",
      "Intelligence"
    ],
    "prerequisite": "Spellcasting or Pact Magic Feature",
    "category": "General"
  },
  {
    "name": "Weapon Master",
    "book": "phb",
    "abilityIncrease": [
      "Strength",
      "Dexterity"
    ],
    "category": "General"
  },
  {
    "name": "Wyrd Magic",
    "book": "echh",
    "prerequisite": "Spellcasting or Pact Magic feature",
    "youGain": "{false}",
    "category": "General"
  },
  {
    "name": "Zhentarim Tactics",
    "book": "hof",
    "abilityIncrease": [
      "Dexterity",
      "Charisma"
    ],
    "prerequisite": "Zhentarim Ruffian Feat",
    "category": "General"
  },
  {
    "name": "Boon of Bloodshed",
    "book": "hof",
    "abilityIncrease": [
      "Strenght",
      "Dexterity",
      "Constitution",
      "Intelligence",
      "Wisdom",
      "Charisma"
    ],
    "category": "General"
  },
  {
    "name": "Boon of Boutiful Health",
    "book": "echh",
    "abilityIncrease": [
      "Strenght",
      "Dexterity",
      "Constitution",
      "Intelligence",
      "Wisdom",
      "Charisma"
    ],
    "category": "General"
  },
  {
    "name": "Boon of Combat Prowess",
    "book": "phb",
    "abilityIncrease": [
      "Charisma",
      "Wisdom",
      "Intelligence",
      "Dexterity",
      "Strength",
      "Constitution"
    ],
    "category": "General"
  },
  {
    "name": "Boon of Communication",
    "book": "hof",
    "abilityIncrease": [
      "Charisma",
      "Wisdom",
      "Intelligence"
    ],
    "category": "General"
  },
  {
    "name": "Boon of Desperate Resilience",
    "book": "hof",
    "abilityIncrease": [
      "Strength",
      "Constitution"
    ],
    "category": "General"
  },
  {
    "name": "Boon of Dimensional Travel",
    "book": "phb",
    "abilityIncrease": [
      "Charisma",
      "Wisdom",
      "Intelligence",
      "Dexterity",
      "Strength",
      "Constitution"
    ],
    "category": "General"
  },
  {
    "name": "Boon of Energy Infusion",
    "book": "phb",
    "abilityIncrease": [
      "Charisma",
      "Wisdom",
      "Intelligence",
      "Dexterity",
      "Strength",
      "Constitution"
    ],
    "category": "General"
  },
  {
    "name": "Boon of Energy Resistance",
    "book": "phb",
    "abilityIncrease": [
      "Charisma",
      "Wisdom",
      "Intelligence",
      "Dexterity",
      "Strength",
      "Constitution"
    ],
    "category": "General"
  },
  {
    "name": "Boon of Exquisite Radiance",
    "book": "hof",
    "abilityIncrease": [
      "Choice"
    ],
    "category": "General"
  },
  {
    "name": "Boon of Fate",
    "book": "phb",
    "abilityIncrease": [
      "Charisma",
      "Wisdom",
      "Intelligence",
      "Dexterity",
      "Strength",
      "Constitution"
    ],
    "category": "General"
  },
  {
    "name": "Boon of Fluid Forms",
    "book": "hof",
    "abilityIncrease": [
      "Charisma",
      "Wisdom",
      "Intelligence"
    ],
    "category": "General"
  },
  {
    "name": "Boon of Fortitude",
    "book": "phb",
    "abilityIncrease": [
      "Charisma",
      "Wisdom",
      "Intelligence",
      "Dexterity",
      "Strength",
      "Constitution"
    ],
    "category": "General"
  },
  {
    "name": "Boon of Fortune's Favor",
    "book": "hof",
    "abilityIncrease": [
      "Choice"
    ],
    "category": "General"
  },
  {
    "name": "Boon of High Magic",
    "book": "echh",
    "youGain": "{false}",
    "category": "General"
  },
  {
    "name": "Boon of Invincibility",
    "book": "echh",
    "abilityIncrease": [
      "Constitution"
    ],
    "youGain": "{false}",
    "category": "General"
  },
  {
    "name": "Boon of Irresistable Offense",
    "book": "phb",
    "abilityIncrease": [
      "Strength",
      "Dexterity"
    ],
    "category": "General"
  },
  {
    "name": "Boon of Legendary Actions",
    "book": "echh",
    "youGain": "{false}",
    "category": "General"
  },
  {
    "name": "Boon of Magic Wellspring",
    "book": "echh",
    "abilityIncrease": [
      "Charisma",
      "Wisdom",
      "Intelligence"
    ],
    "youGain": "{false}",
    "category": "General"
  },
  {
    "name": "Boon of Poison Mastery",
    "book": "hof",
    "abilityIncrease": [
      "Strength",
      "Dexterity",
      "Constitution",
      "Intelligence",
      "Wisdom",
      "Charisma"
    ],
    "category": "General"
  },
  {
    "name": "Boon of Quick Casting",
    "book": "echh",
    "abilityIncrease": [
      "Intelligence",
      "Wisdom",
      "Charisma"
    ],
    "youGain": "{false}",
    "category": "General"
  },
  {
    "name": "Boon of Recovery",
    "book": "phb",
    "abilityIncrease": [
      "Charisma",
      "Wisdom",
      "Intelligence",
      "Dexterity",
      "Strength",
      "Constitution"
    ],
    "category": "General"
  },
  {
    "name": "Boon of Resilience",
    "book": "echh",
    "abilityIncrease": [
      "Constitution"
    ],
    "youGain": "{false}",
    "category": "General"
  },
  {
    "name": "Boon of Revelry",
    "book": "hof",
    "abilityIncrease": [
      "Charisma",
      "Wisdom",
      "Intelligence"
    ],
    "category": "General"
  },
  {
    "name": "Boon of Skill",
    "book": "phb",
    "abilityIncrease": [
      "Charisma",
      "Wisdom",
      "Intelligence",
      "Dexterity",
      "Strength",
      "Constitution"
    ],
    "category": "General"
  },
  {
    "name": "Boon of Speed",
    "book": "phb",
    "abilityIncrease": [
      "Charisma",
      "Wisdom",
      "Intelligence",
      "Dexterity",
      "Strength",
      "Constitution"
    ],
    "category": "General"
  },
  {
    "name": "Boon of Spell Lore",
    "book": "echh",
    "abilityIncrease": [
      "Charisma",
      "Wisdom",
      "Intelligence"
    ],
    "youGain": "{false}",
    "category": "General"
  },
  {
    "name": "Boon of Spell Mastery",
    "book": "echh",
    "category": "General"
  },
  {
    "name": "Boon of Spell Recall",
    "book": "phb",
    "abilityIncrease": [
      "Intelligence",
      "Wisdom",
      "Charisma"
    ],
    "category": "General"
  },
  {
    "name": "Boon of Terror",
    "book": "hof",
    "abilityIncrease": [
      "Charisma"
    ],
    "category": "General"
  },
  {
    "name": "Boon of the Bright Sun",
    "book": "hof",
    "abilityIncrease": [
      "Constitution",
      "Charisma",
      "Wisdom"
    ],
    "category": "General"
  },
  {
    "name": "Boon of the Furious Storm",
    "book": "hof",
    "abilityIncrease": [
      "Charisma",
      "Wisdom",
      "Intelligence"
    ],
    "category": "General"
  },
  {
    "name": "Boon of the Night Spirit",
    "book": "phb",
    "abilityIncrease": [
      "Charisma",
      "Wisdom",
      "Intelligence",
      "Dexterity",
      "Strength",
      "Constitution"
    ],
    "category": "General"
  },
  {
    "name": "Boon of Truesight",
    "book": "phb",
    "abilityIncrease": [
      "Charisma",
      "Wisdom",
      "Intelligence",
      "Dexterity",
      "Strength",
      "Constitution"
    ],
    "category": "General"
  },
  {
    "name": "Boon of the Soul Drinker",
    "book": "hof",
    "abilityIncrease": [
      "Choice"
    ],
    "category": "General"
  },
  {
    "name": "Boon of the True Caster",
    "book": "echh",
    "abilityIncrease": [
      "Charisma",
      "Wisdom",
      "Intelligence"
    ],
    "category": "General"
  },
  {
    "name": "Boon of the Unfettered",
    "book": "echh",
    "abilityIncrease": [
      "Strength",
      "Constitution",
      "Dexterity"
    ],
    "youGain": "{false}",
    "category": "General"
  },
  {
    "name": "Boon of the Warmage",
    "book": "echh",
    "abilityIncrease": [
      "Charisma",
      "Wisdom",
      "Intelligence"
    ],
    "category": "General"
  },
  {
    "name": "Boon of the Witch",
    "book": "echh",
    "abilityIncrease": [
      "Charisma",
      "Wisdom",
      "Intelligence"
    ],
    "youGain": "{false}",
    "category": "General"
  },
  {
    "name": "Boon of Time Mastery",
    "book": "echh",
    "abilityIncrease": [
      "Charisma",
      "Wisdom",
      "Intelligence"
    ],
    "prerequisite": "Arcane Spellcasting, the ability to cast 9th level spells",
    "youGain": "{false}",
    "category": "General"
  },
  {
    "name": "Boon of Unlimited Stamina",
    "book": "echh",
    "abilityIncrease": [
      "Constitution"
    ],
    "youGain": "{false}",
    "category": "General"
  },
  {
    "name": "Alchamaestro",
    "book": "echh",
    "abilityIncrease": [
      "Constitution",
      "Intelligence"
    ],
    "youGain": "{false}",
    "category": "General"
  },
  {
    "name": "Arcane Insight",
    "book": "echh",
    "abilityIncrease": [
      "Charisma",
      "Wisdom",
      "Intelligence"
    ],
    "category": "General"
  },
  {
    "name": "Artifact Affinity",
    "book": "echh",
    "abilityIncrease": [
      "Charisma",
      "Wisdom",
      "Intelligence"
    ],
    "category": "General"
  },
  {
    "name": "Blinding Speed",
    "book": "echh",
    "abilityIncrease": [
      "Dexterity"
    ],
    "youGain": "{false}",
    "category": "General"
  },
  {
    "name": "Boundless Creativity",
    "book": "echh",
    "abilityIncrease": [
      "Intelligence",
      "Wisdom",
      "Charisma"
    ],
    "youGain": "{false}",
    "category": "General"
  },
  {
    "name": "Cavalry Master",
    "book": "echh",
    "abilityIncrease": [
      "Strength",
      "Dexterity",
      "Constitution"
    ],
    "youGain": "{false}",
    "category": "General"
  },
  {
    "name": "Deadshot",
    "book": "echh",
    "abilityIncrease": [
      "Dexterity"
    ],
    "youGain": "{false}",
    "category": "General"
  },
  {
    "name": "Deathbringer",
    "book": "echh",
    "youGain": "{false}",
    "category": "General"
  },
  {
    "name": "Devastating Charger",
    "book": "echh",
    "abilityIncrease": [
      "Strength"
    ],
    "youGain": "{false}",
    "category": "General"
  },
  {
    "name": "Divine Aspect",
    "book": "echh",
    "abilityIncrease": [
      "Charisma",
      "Wisdom",
      "Intelligence"
    ],
    "youGain": "{false}",
    "category": "General"
  },
  {
    "name": "Extraordinary Focus",
    "book": "echh",
    "abilityIncrease": [
      "Charisma",
      "Wisdom",
      "Intelligence"
    ],
    "youGain": "{false}",
    "category": "General"
  },
  {
    "name": "Fist of Fury",
    "book": "echh",
    "youGain": "{false}",
    "category": "General"
  },
  {
    "name": "Flawless Instincts",
    "book": "echh",
    "youGain": "{false}",
    "category": "General"
  },
  {
    "name": "Force of Will",
    "book": "echh",
    "abilityIncrease": [
      "Wisdom"
    ],
    "category": "General"
  },
  {
    "name": "Giver of Life",
    "book": "echh",
    "abilityIncrease": [
      "Charisma",
      "Wisdom",
      "Intelligence"
    ],
    "category": "General"
  },
  {
    "name": "Immortality",
    "book": "echh",
    "abilityIncrease": [
      "Constitution"
    ],
    "youGain": "{false}",
    "category": "General"
  },
  {
    "name": "Impenetrable Bulkwark",
    "book": "echh",
    "youGain": "{false}",
    "category": "General"
  },
  {
    "name": "Legendary Potency",
    "book": "echh",
    "youGain": "{false}",
    "category": "General"
  },
  {
    "name": "Legendary Resistance",
    "book": "echh",
    "youGain": "{false}",
    "category": "General"
  },
  {
    "name": "Legendary Skills",
    "book": "echh",
    "youGain": "{false}",
    "category": "General"
  },
  {
    "name": "Living Armor",
    "book": "echh",
    "abilityIncrease": [
      "Dexterity",
      "Constitution",
      "Strength"
    ],
    "youGain": "{false}",
    "category": "General"
  },
  {
    "name": "Lord of War",
    "book": "echh",
    "abilityIncrease": [
      "Dexterity",
      "Constitution",
      "Strength"
    ],
    "youGain": "{false}",
    "category": "General"
  },
  {
    "name": "Magical Savant",
    "book": "echh",
    "category": "General"
  },
  {
    "name": "Master of Rituals",
    "book": "echh",
    "abilityIncrease": [
      "Charisma",
      "Wisdom",
      "Intelligence"
    ],
    "category": "General"
  },
  {
    "name": "Master of Tactics",
    "book": "echh",
    "youGain": "{false}",
    "category": "General"
  },
  {
    "name": "Might-based Spellcasting",
    "book": "echh",
    "abilityIncrease": [
      "Strength"
    ],
    "youGain": "{false}",
    "category": "General"
  },
  {
    "name": "Mystic Sage",
    "book": "echh",
    "abilityIncrease": [
      "Charisma",
      "Wisdom",
      "Intelligence"
    ],
    "category": "General"
  },
  {
    "name": "Paragon",
    "youGain": "{false}",
    "category": "General"
  },
  {
    "name": "Perfect Health",
    "abilityIncrease": [
      "Constitution"
    ],
    "youGain": "{false}",
    "category": "General"
  },
  {
    "name": "Relentless Warrior",
    "book": "echh",
    "abilityIncrease": [
      "Dexterity"
    ],
    "category": "General"
  },
  {
    "name": "Shadowdancer",
    "book": "echh",
    "abilityIncrease": [
      "Dexterity"
    ],
    "category": "General"
  },
  {
    "name": "Sight Beyond Sight",
    "abilityIncrease": [
      "Wisdom"
    ],
    "youGain": "{false}",
    "category": "General"
  },
  {
    "name": "Songs of Power",
    "book": "echh",
    "category": "General"
  },
  {
    "name": "Spell Lord",
    "abilityIncrease": [
      "Charisma",
      "Wisdom",
      "Intelligence"
    ],
    "category": "General"
  },
  {
    "name": "Spell Reflection",
    "category": "General"
  },
  {
    "name": "Spellslinger",
    "book": "echh",
    "abilityIncrease": [
      "Charisma",
      "Wisdom",
      "Intelligence"
    ],
    "category": "General"
  },
  {
    "name": "Superior Initiative",
    "book": "echh",
    "category": "General"
  },
  {
    "name": "Versatile Mind",
    "book": "echh",
    "abilityIncrease": [
      "Charisma",
      "Wisdom",
      "Intelligence"
    ],
    "category": "General"
  }
];
