/**
 * Which pages the Handbook prints, and in what order.
 *
 * The Handbook is a rendering of the eight `dnd/` house-rule pages, not a second
 * set of pages, so the two questions its route has to answer are which entries
 * it prints and what order it prints them in. Both answers come from the
 * sidebar rather than from here: an artifact that disagreed with the sidebar
 * about what comes first would be a second opinion about its own contents, and
 * the sidebar is where a reader already learned to look.
 *
 * Pure, and a function of its arguments, so the order can be asserted without a
 * browser. See ADR-0020.
 */

export interface HandbookSource {
  /** The docs collection id, which is also the route the page lives at. */
  slug: string;
  /** The title from frontmatter, which is what a sheet is headed with. */
  title: string;
}

/** The docs collection directory the house rules live in. */
export const HANDBOOK_SOURCE_DIRECTORY = 'dnd';

/** Anything this accepts, which is what `getCollection('docs')` hands back. */
export interface HandbookCandidate {
  id: string;
  data: { title: string; sidebar?: { order?: number; hidden?: boolean } };
}

/**
 * Starlight sorts an autogenerated sidebar group by an explicit
 * `sidebar.order`, and by the entry id otherwise. Mirrored rather than
 * reinvented, so the Handbook and the sidebar cannot drift apart when a page
 * gains an order.
 */
const collator = new Intl.Collator('en');

function orderOf(entry: HandbookCandidate): number {
  return entry.data.sidebar?.order ?? Number.POSITIVE_INFINITY;
}

/**
 * The source pages, in the order the sidebar lists them.
 *
 * A hidden page is left out because the sidebar does not list it, and a page
 * outside `dnd/` is left out because it is not a house rule.
 */
export function handbookSourcePages(entries: HandbookCandidate[]): HandbookSource[] {
  return entries
    .filter(
      (entry) =>
        entry.id.startsWith(`${HANDBOOK_SOURCE_DIRECTORY}/`) && entry.data.sidebar?.hidden !== true
    )
    .sort((a, b) => orderOf(a) - orderOf(b) || collator.compare(a.id, b.id))
    .map((entry) => ({ slug: entry.id, title: entry.data.title }));
}