import { describe, expect, it } from 'vitest';

import { handbookSourcePages } from './handbook';

/**
 * The order of the Handbook's source pages is the order the sidebar lists them
 * in, because the sidebar is where a reader already learned to look. Starlight
 * sorts an autogenerated group by an explicit `sidebar.order` when one is set
 * and by the entry id otherwise, so this mirrors that rule rather than
 * inventing one: a Handbook that disagrees with the sidebar about what comes
 * first is a second opinion about its own contents.
 */

interface Entry {
  id: string;
  data: { title: string; sidebar?: { order?: number; hidden?: boolean }; columns?: 1 | 2 };
}

/** The eight `dnd/` entries as the docs collection hands them over. */
const entries: Entry[] = [
  { id: 'dnd/weapon-properties', data: { title: 'Weapon Properties' } },
  { id: 'dnd/classes', data: { title: 'Classes' } },
  { id: 'dnd/character-creation', data: { title: 'Character Creation' } },
  { id: 'dnd/master-armor-table', data: { title: 'Master Armor Table' } },
  { id: 'dnd/weapon-mastery', data: { title: 'Weapon Master Property' } },
  { id: 'dnd/injuries', data: { title: 'Lingering Injuries' } },
  { id: 'dnd/magic', data: { title: 'Magic' } },
  { id: 'dnd/skills', data: { title: 'Skills' } },
];

/** What the sidebar renders, read off a rendered house-rule page. */
const sidebarSlugs = [
  'dnd/character-creation',
  'dnd/classes',
  'dnd/injuries',
  'dnd/magic',
  'dnd/master-armor-table',
  'dnd/skills',
  'dnd/weapon-mastery',
  'dnd/weapon-properties',
];

describe('handbookSourcePages', () => {
  it('lists the source pages in sidebar order', () => {
    expect(handbookSourcePages(entries).map((source) => source.slug)).toEqual(sidebarSlugs);
  });

  // Stated in the ticket as the reason the order needs no second rule of its
  // own: for these eight pages the sidebar order is title-ascending. If a page
  // is ever renamed so the two disagree, this fails and the disagreement is
  // decided on purpose rather than by accident.
  it('lists the source pages title-ascending, which is the sidebar order today', () => {
    const titles = handbookSourcePages(entries).map((source) => source.title);
    const ascending = [...titles].sort((a, b) => a.localeCompare(b, 'en'));

    expect(titles).toEqual(ascending);
  });

  it('carries the title each sheet is headed with', () => {
    expect(handbookSourcePages(entries)[0]).toEqual({
      slug: 'dnd/character-creation',
      title: 'Character Creation',
    });
  });

  it('leaves out pages that are not house rules', () => {
    const withOthers: Entry[] = [
      ...entries,
      { id: 'dnd-tools/dice-roller', data: { title: 'Dice Roller' } },
      { id: 'guides/reading-aloud', data: { title: 'Reading Aloud' } },
    ];

    expect(handbookSourcePages(withOthers)).toHaveLength(8);
  });

  it('leaves out a house-rule page the sidebar hides', () => {
    const withHidden: Entry[] = [
      ...entries,
      { id: 'dnd/draft-rule', data: { title: 'Draft Rule', sidebar: { hidden: true } } },
    ];

    expect(handbookSourcePages(withHidden).map((source) => source.slug)).not.toContain('dnd/draft-rule');
  });

  describe('the column count each page opts into', () => {
    // The key is declared through the schema's `extend` option rather than added
    // as a bare frontmatter key, because Starlight's default schema is a Zod
    // object in strip mode and would drop it silently. See
    // `src/content/docs/handbook-columns-schema.test.ts` for the parsing side;
    // this is the side that has to *use* what parsing kept.
    it('carries a single-column opt-out through to the sheet', () => {
      // Typed as the literal `1` rather than widened to `number`: the entry
      // interface says the key is `1 | 2` because those are the two layouts the
      // print stylesheet implements, and a test that widened it would let a
      // `columns: 3` through the very type that is supposed to prevent one.
      const single: Entry[] = entries.map((entry) =>
        entry.id === 'dnd/skills' ? { ...entry, data: { ...entry.data, columns: 1 as const } } : entry
      );

      expect(handbookSourcePages(single).find((source) => source.slug === 'dnd/skills')?.columns).toBe(1);
    });

    it('carries nothing for a page that does not ask, so the stylesheet decides', () => {
      // `undefined` rather than a default of 2: the two-column default belongs
      // to the one stylesheet that lays sheets out, and a second copy of it in
      // this function is two numbers that can disagree.
      expect(handbookSourcePages(entries)[0]).not.toHaveProperty('columns');
    });
  });

  // Starlight's rule: an explicit order wins, and an entry without one sorts
  // after every entry that has one.
  it('puts an explicitly ordered source page before the unordered ones', () => {
    const withOrder: Entry[] = [
      ...entries,
      { id: 'dnd/zzz-late', data: { title: 'Late Rule', sidebar: { order: 1 } } },
    ];

    expect(handbookSourcePages(withOrder).map((source) => source.slug)).toEqual([
      'dnd/zzz-late',
      ...sidebarSlugs,
    ]);
  });
});