/**
 * Which pages the Handbook prints, and in what order.
 *
 * The Handbook is a rendering of the eight `dnd/` house-rule pages, not a second
 * set of pages, so the two questions its route has to answer are which entries
 * it prints and what order it prints them in. Both answers come from the
 * sidebar rather than from here: an artifact that disagreed with the sidebar
 * about what comes first would be a second opinion about its own contents, and
 * the sidebar is where a reader already learned to look.
 *
 * Pure, and a function of its arguments, so the order can be asserted without a
 * browser. See ADR-0020.
 */

/**
 * The Handbook's title, as the cover sheet prints it and as the publisher page
 * names it.
 *
 * One string for both, because a cover and a page that disagree about what the
 * thing is called are two names for one book and a reader holding either of them
 * would not know they are holding the same one.
 */
export const HANDBOOK_TITLE = 'D&D House Rules Handbook';

/**
 * The edition the artifact is, stated on the cover and on the publisher page.
 *
 * A PDF of house rules has to say what version it is before it can be trusted at
 * a table, and a manifest hash is not that: it tells a maintainer whether the
 * file is stale, and tells a reader nothing. Bumped by hand, because an edition
 * is a decision somebody makes rather than a number a build derives.
 */
export const HANDBOOK_VERSION = '1.0';

/**
 * The day this edition was cut, in ISO form so it sorts and compares as a date
 * rather than as prose.
 *
 * Both surfaces again: a reader who wants to know whether the copy on the table
 * is the one this site is serving should not have to infer it from a file name.
 */
export const HANDBOOK_EDITION_DATE = '2026-10-04';

/**
 * Where the artifact is published, which is what the publisher page links to.
 *
 * The path the command writes, so a link on the site and a file on disk are the
 * same path rather than two that agree today.
 */
export const HANDBOOK_FILE = '/handbook/handbook.pdf';

/**
 * The download as one line, for the cover and the publisher page to share.
 *
 * "Version 1.0, edition 2026-10-04" rather than two labelled fields, because a
 * book states its edition on one line and a reader reads a cover rather than a
 * form.
 */
export const HANDBOOK_EDITION = `Version ${HANDBOOK_VERSION}, edition ${HANDBOOK_EDITION_DATE}`;

export interface HandbookSource {
  /** The docs collection id, which is also the route the page lives at. */
  slug: string;
  /** The title from frontmatter, which is what a sheet is headed with. */
  title: string;
  /**
   * The page's own column count, when it opts out of the two-column sheet.
   *
   * Absent rather than defaulted. The two-column default is the print
   * stylesheet's to apply, and a second copy of it here is two numbers that can
   * disagree; carrying `undefined` lets the stylesheet be the only place the
   * default is written down.
   */
  columns?: 1 | 2;
}

/** The docs collection directory the house rules live in. */
export const HANDBOOK_SOURCE_DIRECTORY = 'dnd';

/** Anything this accepts, which is what `getCollection('docs')` hands back. */
export interface HandbookCandidate {
  id: string;
  data: { title: string; sidebar?: { order?: number; hidden?: boolean }; columns?: 1 | 2 };
}

/**
 * Starlight sorts an autogenerated sidebar group by an explicit
 * `sidebar.order`, and by the entry id otherwise. Mirrored rather than
 * reinvented, so the Handbook and the sidebar cannot drift apart when a page
 * gains an order.
 */
const collator = new Intl.Collator('en');

function orderOf(entry: HandbookCandidate): number {
  return entry.data.sidebar?.order ?? Number.POSITIVE_INFINITY;
}

/**
 * The source pages, in the order the sidebar lists them.
 *
 * A hidden page is left out because the sidebar does not list it, and a page
 * outside `dnd/` is left out because it is not a house rule.
 */
export function handbookSourcePages(entries: HandbookCandidate[]): HandbookSource[] {
  return entries
    .filter(
      (entry) =>
        entry.id.startsWith(`${HANDBOOK_SOURCE_DIRECTORY}/`) && entry.data.sidebar?.hidden !== true
    )
    .sort((a, b) => orderOf(a) - orderOf(b) || collator.compare(a.id, b.id))
    .map((entry) =>
      // `columns` is spread rather than named so a page that does not set it
      // carries no key at all, which is what keeps the stylesheet the only place
      // the two-column default is written down.
      ({ slug: entry.id, title: entry.data.title, ...(entry.data.columns ? { columns: entry.data.columns } : {}) })
    );
}