import { readFileSync, writeFileSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const FEATS_PATH = resolve(__dirname, '../../golden-forest/docs/Games/DnD/feats.md');
const OUTPUT_PATH = resolve(__dirname, '../src/components/feats-explorer/feat-data.js');

const BOOKS = {
  phb: "Player's Handbook",
  hof: "Heroes of Faerûn",
  fef: "Fifth Edition Feats",
  echh: "Epic Characters & Heroes Handbook"
};

const ABILITIES = ['Strength', 'Dexterity', 'Constitution', 'Intelligence', 'Wisdom', 'Charisma'];

function extractFeats(content) {
  const feats = [];
  const featRegex = /<Feat\s+([^>]+)>/g;
  let match;
  
  while ((match = featRegex.exec(content)) !== null) {
    const propsString = match[1];
    const feat = {};
    
    // Extract name
    const nameMatch = propsString.match(/name="([^"]+)"/);
    if (nameMatch) {
      feat.name = nameMatch[1];
    }
    
    // Extract level
    const levelMatch = propsString.match(/level=\{?(\d+)\}?/);
    if (levelMatch) {
      feat.level = parseInt(levelMatch[1], 10);
    }
    
    // Extract book
    const bookMatch = propsString.match(/book="([^"]+)"/);
    if (bookMatch) {
      feat.book = bookMatch[1];
    }
    
    // Extract abilityIncrease (array)
    const abilityMatch = propsString.match(/abilityIncrease=\{?\[([^\]]*)\]\}?/);
    if (abilityMatch) {
      const abilities = abilityMatch[1].split(',').map(a => a.trim().replace(/"/g, ''));
      feat.abilityIncrease = abilities;
    }
    
    // Extract prerequisite
    const prereqMatch = propsString.match(/prerequisite="([^"]+)"/);
    if (prereqMatch) {
      feat.prerequisite = prereqMatch[1];
    }
    
    // Extract youGain
    const youGainMatch = propsString.match(/youGain="?([^"\s>]+)"?/);
    if (youGainMatch) {
      const value = youGainMatch[1];
      if (value === 'true') {
        feat.youGain = true;
      } else if (value === 'false') {
        feat.youGain = false;
      } else {
        feat.youGain = value;
      }
    }
    
    // Determine category based on level
    feat.category = feat.level === 0 ? 'Origin' : 'General';
    
    // Extract description (text between opening and closing tags)
    const fullMatch = content.substring(match.index, content.indexOf('</Feat>', match.index));
    const descriptionMatch = fullMatch.match(/<\/Feat[^>]*>([\s\S]*?)(?=<\/?Feat|$)/);
    if (descriptionMatch) {
      const description = descriptionMatch[1]
        .replace(/\n/g, ' ')
        .replace(/\s+/g, ' ')
        .trim();
      feat.description = description.substring(0, 200) + (description.length > 200 ? '...' : '');
    }
    
    feats.push(feat);
  }
  
  return feats;
}

function generateOutput(feats) {
  return `// Auto-generated by extract-feats.js
// Do not edit manually

export const BOOKS = ${JSON.stringify(BOOKS, null, 2)};

export const ABILITIES = ${JSON.stringify(ABILITIES, null, 2)};

export const FEATS = ${JSON.stringify(feats, null, 2)};
`;
}

try {
  const content = readFileSync(FEATS_PATH, 'utf8');
  const feats = extractFeats(content);
  const output = generateOutput(feats);
  writeFileSync(OUTPUT_PATH, output, 'utf8');
  console.log(`Extracted ${feats.length} feats to ${OUTPUT_PATH}`);
} catch (error) {
  console.error('Error extracting feats:', error);
  process.exit(1);
}
